import { Box, Container, Text, Title } from "@mantine/core";

import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextJS Lambda</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/dev/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Title order={1}>Welcome to this NextJS Lambda!</Title>
          <Text>This is a standalone NextJS Lambda with Mantine</Text>

          <Box py={20}>
            <Text>Super high-level diagram:</Text>
            <Image
              height={200}
              width={600}
              src="/dev/diagram.png"
              alt="simplified diagram of user flow, user request content through api gateway, api gateway calls nextjs lambda, lambda returns server side rendered content."
            />
          </Box>
        </Container>
      </main>
    </>
  );
}
